apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: new-container
          image: jivedh2019/assign_2:IMAGE_TAG
          ports:
            - containerPort: 8080
